### ISSUE TITLE
Feature request: being able to see what's in the queue

### ISSUE THREAD

**Issue by LaurinDemmler** [joshuajeschek/dandelion#4]
Would be great if one´d be able to see what is in the queue and maybe even amend it.

**Comment by joshuajeschek** [comment]
![image](https://user-images.githubusercontent.com/64850647/158695517-9d2aa3d8-d2ba-4434-9166-f9baaba12ac1.png)
that's already possible. Maybe I will introduce a remove command to remove a specific song from a queue.
